name: matchms
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gensim==3.8.0
  - matplotlib==3.2.1
  - numpy==1.18.1
  - openbabel==3.0.0
  - pip==20.0.2
  - pyteomics==4.2
  - python==3.7
  - pyyaml==5.3.1
  - rdkit==2020.03.1
  - scipy==1.4.1
  - pip:
    - docstr-coverage
    - isort
    - prospector[with_pyroma]
    - pycodestyle
    - pytest
    - pytest-cov
    - pytest-runner
    - recommonmark
    - ruamel.yaml
    - sphinx
    - sphinx_rtd_theme
    - yapf
