# Build commmand:
# conda build -c conda-forge -c bioconda -c nlesc .

{% set name = "matchms" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # git_rev: master
  # git_url: https://github.com/matchms/matchms.git
  path: .

extra:
  channels:
    - conda-forge
    - bioconda
    - nlesc

build:
  noarch: python
  number: 0
  script: {{PYTHON}} -m pip install --no-deps .

requirements:
  build:
    - pytest-runner==5.2
  host:
    - python==3.7
    - pip==20.0.2
    - pytest-runner==5.2
    - setuptools==46.1.3
  run:
    - python==3.7
    - matplotlib==3.2.1
    - numpy==1.18.1
    - pyyaml==5.3.1
    - pycodestyle==2.5.0
    - pytest==5.4.1
    - pytest-cov==2.8.1
    - pyteomics==4.2
    - scipy==1.4.1
test:
  imports:
    - matchms

about:
  home: https://github.com/matchms/matchms
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Vector representation of mass spectral data (e.g. MS-MS) and spectral similarity measure. '
  description: |
    Vector representation of mass spectral data (e.g. MS-MS) and
    spectral similarity measure.
  doc_url: https://matchms.readthedocs.io/
  dev_url: https://github.com/matchms/matchms

extra:
  recipe-maintainers:
    - fdiblen
