name: 'Anaconda Build and Publish'

on:
  release:
    types: [published]

jobs:

  publish:
    name: Publish conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: matchms
          auto-activate-base: false
          channels: conda-forge,bioconda,nlesc
      - name: Install required packages
        shell: bash -l {0}
        run: |
          conda install conda-build conda-verify anaconda
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload no
          export BUILD_FOLDER=./output
          export BUILD_DATE=`date +%Y.%m.%d`
          mkdir -p $BUILD_FOLDER
          conda build -c bioconda -c conda-forge -c nlesc --output-folder $BUILD_FOLDER .
      - name: Push the package to anaconda cloud
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER=./output
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u nlesc --force $BUILD_FOLDER/noarch/*.tar.bz2
